/* Guided design workflow, wall clearances and portable presentation reports. */
(function(){
 'use strict';
 const D=FurnishDesign,P=FurnishProject,clone=v=>JSON.parse(JSON.stringify(v));
 const sides={left:['左侧','Left'],right:['右侧','Right'],top:['上侧','Top'],bottom:['下侧','Bottom']};
 const useName=id=>tr(...D.uses[id]);
 function recovery(){const entries=hist.filter(h=>h.planId===PLAN.id);openDialog({title:tr('恢复记录','Recovery points'),wide:true,body:`<p>${tr('编辑前定期保留快照；清空、重置、载入方案或项目前额外保留恢复点。每个户型最多 8 条，预览确认后恢复。','Periodic snapshots preserve earlier edits; clearing, resetting or loading a design/project creates an extra recovery point. Preview before restoring; up to 8 per plan.')}</p>${historySaveErr?`<p class="project-error">${tr('恢复记录尚未写入本地存储，请导出项目文件备份。','Recovery points could not be persisted; export a project backup.')}</p>`:''}<button class="btn primary" id="recovery-create">${tr('保留当前恢复点','Keep a recovery point')}</button><div style="display:grid;gap:10px;margin-top:14px">${entries.map(h=>`<button class="btn" data-recovery-preview="${h.ts}" style="text-align:left;white-space:normal;line-height:1.7">${esc(new Date(h.ts).toLocaleString())} · ${esc(h.reason||'历史快照')}<br>${h.n} ${tr('件家具','items')} · ${tr('预览／恢复','Preview / restore')}</button>`).join('')||`<p>${tr('暂无恢复记录','No recovery points yet')}</p>`}</div>`,actions:[{label:tr('关闭','Close')}],onOpen:()=>{$('#recovery-create').onclick=()=>{snapshot(true,state,'手动保留');recovery();};document.querySelectorAll('[data-recovery-preview]').forEach(b=>b.onclick=()=>previewRecovery(Number(b.dataset.recoveryPreview)));}});}
 function previewRecovery(ts){const h=hist.find(h=>h.ts===ts&&h.planId===PLAN.id);if(!h)return;let next,plan;try{next=fixWork(P.validateWork(h.data),PLAN);plan=P.effectivePlan(PLAN,next);}catch(e){return toast(e.message);}const b=plan.bounds;let preview=planThumb(plan);const furniture=next.furniture.map(f=>`<polygon points="${P.polygon(f).map(p=>p.join(',')).join(' ')}" fill="${/^#[0-9a-f]{3,8}$/i.test(f.color)?f.color:'#d3bd9b'}" stroke="#685c4f" stroke-width="15"/>`).join('');preview=preview.replace('</svg>',furniture+'</svg>');
  openDialog({title:tr('预览恢复点','Preview recovery point'),wide:true,body:`<p>${esc(new Date(h.ts).toLocaleString())} · ${esc(h.reason||'历史快照')}</p><p>${tr('当前','Current')}: ${state.furniture.length} ${tr('件家具；恢复点','items; recovery point')}: ${next.furniture.length} ${tr('件家具','items')} · ${P.quantities(plan,next.architecture).net.toFixed(2)} m²</p>${preview.replace('<svg ','<svg class="project-thumb" ')}<p>${tr('恢复前会保留当前工作内容，恢复后也可撤销。已确认的原始承重结构继续受到保护。','The current work is saved before recovery; restoring is undoable. Confirmed original structure remains protected.')}</p><p id="recovery-error" class="project-error" role="alert"></p>`,actions:[{label:tr('取消','Cancel')},{label:tr('导出此恢复点','Export this point'),fn:()=>{try{const packed=P.pack({planId:PLAN.id,name:PLAN.name,current:clone(next),designs:[],catalog:clone(store.custom||[])});P.unpack(packed);download('恢复点-'+h.ts+'.furnish.json',new Blob([JSON.stringify(packed,null,2)],{type:'application/json'}));}catch(e){$('#recovery-error').textContent=e.message;}return false;}},{label:tr('恢复到此记录','Restore this point'),cls:'primary',fn:()=>{try{if(state.architecture)next.architecture=P.protectOriginal(state.architecture,next.architecture);snapshot(true,state,'恢复记录前');const before=snap();state=clone(next);ui.sel=null;commit(before);renderAll();toast(tr('已恢复，可撤销或从恢复记录找回原布置。','Restored; undo or use recovery points to retrieve the prior layout.'));return true;}catch(e){$('#recovery-error').textContent=e.message;return false;}}}]});
 }
 function saveDesignAction(action,options){const next=D.manageDesign(store.designs,PLAN.id,action,options),old=store.designs.find(d=>d.id===options.id&&d.planId===PLAN.id);if(old&&['update','delete'].includes(action))snapshot(true,old.work,(action==='update'?'更新命名方案前：':'删除命名方案前：')+old.name);store.designs=next;save();renderDesigns();toast(tr('方案管理已保存','Design library saved'));}
 function editDesign(action,id){const d=store.designs.find(d=>d.id===id&&d.planId===PLAN.id);if(action!=='create'&&!d)return;
  let name=d?.name||tr('方案','Design')+' '+(store.designs.filter(d=>d.planId===PLAN.id).length+1);if(action==='duplicate'){const base=name.slice(0,65);let n=1;do{name=base+' · 副本 '+n++;}while(store.designs.some(d=>d.planId===PLAN.id&&d.name===name));}
  const labels={create:['保存当前方案','Save current design'],rename:['编辑名称与备注','Edit name & notes'],update:['用当前布置更新方案','Update with current work'],duplicate:['复制命名方案','Duplicate design'],delete:['删除命名方案','Delete design']};
  openDialog({title:tr(...labels[action]),body:action==='delete'?`<p>${tr('删除','Delete')}「${esc(d.name)}」？${tr('当前画布布置会保留，备份文件中的方案不受影响。','The current canvas and exported backups are retained.')}</p>`:`${action==='update'?`<p class="project-note">${tr('将覆盖此方案的墙体、家具、材料、预算和三维展示设置。当前画布不会改变。','Replace this saved design with the current walls, furniture, materials, costs and 3D settings.')}</p>`:''}<div class="project-grid"><label>${tr('方案名称','Name')}<input id="design-name" maxlength="80" value="${esc(name)}"></label><label>${tr('备注','Notes')}<textarea id="design-note" maxlength="500" rows="3">${esc((action==='create'||action==='update'?state:d.work).designNote||'')}</textarea></label></div><p id="design-error" class="project-error" role="alert"></p>`,actions:[{label:tr('取消','Cancel')},{label:action==='delete'?tr('确认删除','Delete'):tr('保存','Save'),cls:action==='delete'?'danger':'primary',fn:()=>{try{saveDesignAction(action,{id,name:$('#design-name')?.value,work:clone(state),note:$('#design-note')?.value});return true;}catch(e){const target=$('#design-error');if(target)target.textContent=e.message;else toast(e.message);return false;}}}]});
 }
 function designs(){const rows=store.designs.filter(d=>d.planId===PLAN.id);openDialog({title:tr('命名方案管理','Saved designs'),wide:true,body:`<p>${tr('保存独立版本；复制已有方案后可载入继续修改。更新会用当前画布覆盖指定版本。','Keep independent versions; duplicate and load a design to continue editing. Updating replaces a selected version with the current canvas.')}</p><button class="btn primary" id="design-create">${tr('保存当前方案','Save current design')}</button><div style="display:grid;gap:12px;margin-top:16px">${rows.map(d=>`<article style="padding:14px;border:1px solid var(--line);border-radius:12px;overflow-wrap:anywhere"><b>${esc(d.name)}</b><p class="project-note">${d.work.furniture.length} ${tr('件家具','items')} · ${esc(new Date(d.ts).toLocaleString())}<br>${esc(d.work.designNote||tr('无备注','No notes'))}</p><div style="display:flex;flex-wrap:wrap;gap:6px">${[['load','载入','Load'],['rename','名称／备注','Name / notes'],['update','用当前布置更新','Update from canvas'],['duplicate','复制','Duplicate'],['delete','删除','Delete']].map(([action,zh,en])=>`<button class="btn ${action==='delete'?'danger':''}" data-design-action="${action}" data-design-id="${esc(d.id)}">${tr(zh,en)}</button>`).join('')}</div></article>`).join('')||`<p>${tr('暂无已保存方案','No saved designs')}</p>`}</div>`,actions:[{label:tr('关闭','Close')}],onOpen:()=>{$('#design-create').onclick=()=>editDesign('create');document.querySelectorAll('[data-design-action]').forEach(b=>b.onclick=()=>{if(b.dataset.designAction==='load'){closeDialog();document.querySelector(`[data-dload="${CSS.escape(b.dataset.designId)}"]`)?.click();}else editDesign(b.dataset.designAction,b.dataset.designId);});}});}
 function placementPanel(f){const plan=P.effectivePlan(PLAN,state),gaps=D.wallGaps(plan,f),issues=P.spaceCheck(plan,state.furniture,{focusId:f.id,scanPassages:false});
  return `<h3>${tr('尺寸调整基准','Resize anchor')}</h3><div class="form"><label class="full">${tr('固定位置','Fixed position')}<select id="resizeAnchor" ${f.locked?'disabled':''}>${Object.entries(D.resizeAnchors).map(([id,label])=>`<option value="${id}" ${id===(f.resizeAnchor||'center')?'selected':''}>${tr(...label)}</option>`).join('')}</select></label></div><p class="muted">${tr('改宽／深时保持所选占地边缘位置；旋转家具以平面外包框为准。','Resizing preserves the selected footprint edge; rotated items use their plan bounds.')}</p><h3>${tr('布置检查','Placement check')}</h3><div id="fit-feedback" role="status">${issues.length?issues.map(v=>`<p class="project-error">${esc(v.message)}${v.kind==='overlap'?' · '+esc(v.name):''}</p>`).join(''):`<p class="muted">${tr('本轮占地与开启空间检查未发现问题。','No footprint or opening-space issues found.')}</p>`}</div><button class="btn" id="fit-check">${tr('打开全案空间检查','Check entire design')}</button><h3>${tr('精准距墙','Wall clearance')}</h3><p class="muted">${tr('从家具旋转后的外边缘量至对应墙面；输入 0 可贴墙。','Measured from the rotated footprint edge to the wall. Enter 0 to touch the wall.')}</p><div class="form">${Object.entries(sides).map(([id,label])=>`<label>${tr(...label)} mm<input type="number" data-wall-gap="${id}" aria-label="${tr(...label)}距墙 mm" value="${gaps[id]?Math.round(gaps[id].gap):''}" placeholder="${tr('无对应墙面','No wall')}" min="0" max="20000" step="1" ${f.locked||!gaps[id]?'disabled':''}></label>`).join('')}</div><p id="placement-error" class="project-error" role="alert"></p>`;
 }
 function groupPlacementPanel(items){
  const issues=P.spaceCheck(P.effectivePlan(PLAN,state),state.furniture,{focusIds:items.map(f=>f.id),scanPassages:false,maxIssues:7}),locked=items.filter(f=>f.locked).length;
  return `<h3>${tr('整组布置检查','Group placement check')}</h3><div id="group-fit-feedback" role="status">${issues.length?issues.slice(0,6).map(v=>`<p class="project-error">${esc(v.name)} · ${esc(v.message)}</p>`).join('')+(issues.length>6?`<p class="muted">${tr('还有其他问题，请打开全案检查。','More issues found; open the full check.')}</p>`:''):`<p class="muted">${tr('选中项本轮占地与开启空间检查未发现问题。','No footprint or opening-space issues found for the selected items.')}</p>`}</div><button class="btn" data-act="spaceCheck">${tr('打开全案空间检查','Check entire design')}</button><p class="muted note">${tr('统一尺寸和恢复默认尺寸沿用每件家具的尺寸调整基准。','Match size and reset size preserve each item’s resize anchor.')}${locked?' '+tr(`${locked} 件已锁定，几何调整将跳过。`,`${locked} locked items will be skipped for geometry changes.`):''}</p>`;
 }
 function clearPlacementGuide(){$('#gPlacement')?.remove();}
 function placementGuide(f,dir){
  clearPlacementGuide();const gap=D.wallGaps(P.effectivePlan(PLAN,state),f)[dir];if(!gap)return;const box=D.bounds(f),axis=gap.axis,other=1-axis,across=(Math.max(box[other],gap.wall[other])+Math.min(box[other+2],gap.wall[other+2]))/2;
  const start=[0,0],end=[0,0];start[other]=end[other]=across;start[axis]=gap.edge;end[axis]=box[gap.sign===1?axis:axis+2];
  const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.id='gPlacement';g.setAttribute('pointer-events','none');const size=13/view.s;
  g.innerHTML=`<line x1="${gap.wall[0]}" y1="${gap.wall[1]}" x2="${axis?gap.wall[2]:gap.wall[0]}" y2="${axis?gap.wall[1]:gap.wall[3]}" stroke="#ef5a24" stroke-width="3" vector-effect="non-scaling-stroke"/><line x1="${start[0]}" y1="${start[1]}" x2="${end[0]}" y2="${end[1]}" stroke="#ef5a24" stroke-width="2" vector-effect="non-scaling-stroke"/><text x="${(start[0]+end[0])/2}" y="${(start[1]+end[1])/2-size*.6}" font-size="${size}" text-anchor="middle" fill="#d64d19" stroke="${PAL.paper}" stroke-width="${size*.25}" paint-order="stroke">${Math.round(gap.gap)} mm</text>`;
  // Highlight the same wall face used by the numeric clearance.
  const wallLine=g.firstElementChild;if(axis===0){wallLine.setAttribute('x1',gap.edge);wallLine.setAttribute('x2',gap.edge);}else{wallLine.setAttribute('y1',gap.edge);wallLine.setAttribute('y2',gap.edge);}svg.append(g);
 }
 function bindPlacement(f){$('#resizeAnchor').onchange=e=>mutate(()=>getF(f.id).resizeAnchor=e.target.value);$('#fit-check').onclick=()=>{FurnishWorkspace.open('space');$('#space-run').click();};for(const id of ['fW','fD','fH','fX','fY','fR']){const field=$('#'+id);if(field)field.disabled=!!f.locked;}document.querySelectorAll('#panel [data-wall-gap]').forEach(input=>{input.onfocus=()=>placementGuide(getF(f.id),input.dataset.wallGap);input.onblur=clearPlacementGuide;input.onchange=()=>{try{if(!input.value.trim())throw Error('请输入距墙尺寸');const next=D.placeAtGap(P.effectivePlan(PLAN,state),getF(f.id),input.dataset.wallGap,Number(input.value));mutate(()=>Object.assign(getF(f.id),{cx:next.cx,cy:next.cy}));}catch(e){$('#placement-error').textContent=e.message;}};});}
 function options(room,setting){const use=D.inferUse(room,setting);return Object.entries(D.uses).filter(([id])=>room.counted===false?id==='bay':id!=='bay').map(([id,n])=>`<option value="${id}" ${id===use?'selected':''}>${tr(...n)}</option>`).join('');}
 function workflow(){
  const normal=ROOMS.filter(r=>r.counted!==false),classified=normal.filter(r=>D.inferUse(r,state.rooms[r.id])!=='unassigned').length,designs=store.designs.filter(d=>d.planId===PLAN.id);
  openDialog({title:tr('装修设计工作台','Design workflow'),wide:true,body:`<div class="project-grid"><div><h4>1 · ${tr('确认户型','Verify plan')}</h4><p>${normal.length} ${tr('个房间','rooms')} · ${P.quantities(PLAN).net.toFixed(2)} m²</p><button class="btn" data-flow="edit">${tr('编辑墙体／门窗','Edit walls / openings')}</button></div><div><h4>2 · ${tr('房间用途','Room uses')}</h4><p>${classified} / ${normal.length} ${tr('已分类','classified')}</p><button class="btn primary" data-flow="rooms">${tr('设置房间用途','Set room uses')}</button></div><div><h4>3 · ${tr('家具与材料','Furniture & materials')}</h4><p>${state.furniture.length} ${tr('件家具','items')}</p><button class="btn" data-flow="furniture">${tr('返回画布布置','Arrange on canvas')}</button><button class="btn" data-flow="purchases">${tr('采购清单','Purchase list')}</button><button class="btn" data-flow="space">${tr('检查使用空间','Check clearances')}</button></div><div><h4>4 · ${tr('比较方案','Compare designs')}</h4><p>${designs.length} ${tr('份已保存方案','saved designs')}</p><button class="btn" data-flow="compare">${tr('保存／比较方案','Save / compare')}</button><button class="btn" data-flow="budget">${tr('工程预算','Renovation costs')}</button></div><div><h4>5 · ${tr('交付与分享','Deliver & share')}</h4><p>${tr('平面、效果图、清单和预算合为一份成果。','Plan, views, item list and costs in one document.')}</p><button class="btn primary" data-flow="delivery">${tr('导出方案成果','Export design report')}</button><button class="btn" data-flow="backup">${tr('备份／加载项目','Back up / load')}</button></div></div>`,actions:[{label:tr('关闭','Close')}],onOpen:()=>document.querySelectorAll('[data-flow]').forEach(b=>b.onclick=()=>{const tab=b.dataset.flow;closeDialog();if(tab==='rooms')roomUses();else if(tab==='delivery')delivery();else if(tab==='edit')FurnishEditor.open();else if(tab==='furniture'){ui.sel=null;renderAll();toast(tr('点击房间设置材料；选中家具可输入精准距墙尺寸。','Select rooms for flooring, or furniture for wall clearance.'));}else FurnishWorkspace.open(tab);})});
 }
 function roomUses(){openDialog({title:tr('房间用途与名称','Room uses & names'),wide:true,body:`<p>${tr('用途与名称独立保存；风格方案优先使用用途。厨房、卫生间、阳台和飘窗台保留各自材料。','Room use is saved separately from the name. Styles preserve wet rooms, balconies and bay platforms.')}</p><div class="room-use-list">${ROOMS.map(r=>`<div class="project-grid" style="margin:12px 0"><label>${tr('名称','Name')}<input data-room-name="${r.id}" maxlength="80" value="${esc(state.rooms[r.id].name)}"></label><label>${tr('用途','Use')}<select data-room-use="${r.id}" ${r.counted===false?'disabled':''}>${options(r,state.rooms[r.id])}</select></label><span>${area(r.poly).toFixed(2)} m²${r.counted===false?' · 不计入套内面积':''}</span></div>`).join('')}</div>`,actions:[{label:tr('取消','Cancel')},{label:tr('保存房间设置','Save room settings'),cls:'primary',fn:()=>{const values=ROOMS.map(r=>({id:r.id,name:$(`[data-room-name="${r.id}"]`).value.trim()||state.rooms[r.id].name,use:$(`[data-room-use="${r.id}"]`).value}));mutate(()=>values.forEach(v=>Object.assign(state.rooms[v.id],{name:v.name,use:v.use})));return true;}}]});}
 function floorplanSVG({dimensions=true,measurements=true,notes=true}={}){
  const s=svg.cloneNode(true);s.setAttribute('id','report-plan');s.removeAttribute('style');s.removeAttribute('class');
  s.querySelectorAll('#gSel,#gGrid,#gSpaceFocus,#gGuides,#gPlacement,[data-edit-overlay],script,foreignObject').forEach(g=>g.remove());
  for(const id of ['gRooms','gWalls','gOpen','gFurn','gLabels','gDims','gNotes'])s.querySelector('#'+id)?.removeAttribute('display');
  if(!dimensions)s.querySelector('#gDims')?.remove();if(!notes)s.querySelector('#gNotes')?.remove();
  const measure=s.querySelector('#gMeasure');if(measure){measure.innerHTML=measurements?(state.measures||[]).map(m=>{const v=D.measurementGeometry(m);if(!v)return '';const {a,b}=m,{nx,ny,mx,my,angle,textSize,length}=v;return `<g data-saved-measure="true"><path d="M${a.x} ${a.y}L${b.x} ${b.y}M${a.x-nx} ${a.y-ny}L${a.x+nx} ${a.y+ny}M${b.x-nx} ${b.y-ny}L${b.x+nx} ${b.y+ny}" fill="none" stroke="#ef5a24" stroke-width="1.5" vector-effect="non-scaling-stroke"/><text x="${mx}" y="${my-textSize*.5}" font-size="${textSize}" text-anchor="middle" fill="#ef5a24" transform="rotate(${angle} ${mx} ${my})" stroke="${PAL_LIGHT.halo}" stroke-width="45" paint-order="stroke">${Math.round(length)} mm</text></g>`;}).join(''):'';}
  // Normalize structural colours only; chosen furniture colours stay unchanged.
  for(const id of ['gRooms','gWalls','gOpen','gLabels','gDims'])for(const e of s.querySelectorAll('#'+id+' *'))for(const attr of ['fill','stroke']){const value=e.getAttribute(attr),key=Object.keys(PAL).find(k=>PAL[k]===value);if(key)e.setAttribute(attr,PAL_LIGHT[key]);}
  for(const e of s.querySelectorAll('#gFurn [stroke]'))if(e.getAttribute('stroke')===PAL.ink)e.setAttribute('stroke',PAL_LIGHT.ink);
  for(const e of s.querySelectorAll('#gFurn text'))if(e.getAttribute('fill')===PAL.text)e.setAttribute('fill',PAL_LIGHT.text);
  for(const e of s.querySelectorAll('#gWalls [data-wall]')){const index=Number(e.getAttribute('data-wall').slice(1));if(WALLS[index]?.[4]==='b'&&e.getAttribute('fill')==='#c8553c')e.setAttribute('fill',PAL_LIGHT.wallB);}
  const host=document.createElement('div');host.style.cssText='position:fixed;left:-100000px;top:0;width:1200px;height:650px;visibility:hidden;pointer-events:none';host.append(s);document.body.append(host);let b;
  try{const box=s.getBBox();b=D.deliveryBounds(BOUNDS,[[box.x,box.y,box.x+box.width,box.y+box.height]]);}finally{host.remove();}
  s.setAttribute('viewBox',`${b.x} ${b.y} ${b.w} ${b.h}`);s.setAttribute('width','1200');s.setAttribute('height',String(Math.ceil(1200*b.h/b.w)));
  const bg=document.createElementNS('http://www.w3.org/2000/svg','rect');for(const [name,value] of Object.entries({x:b.x,y:b.y,width:b.w,height:b.h,fill:'#fffaf4'}))bg.setAttribute(name,value);s.insertBefore(bg,s.firstChild);
  return new XMLSerializer().serializeToString(s);
 }
 function reportHTML(title,note,include3D,drawingOptions){
  const plan=P.effectivePlan(PLAN,state),stats=FurnishWorkspace.summary(state),q=P.quantities(plan,state.architecture),payload=P.pack({planId:PLAN.id,name:PLAN.name,current:clone(state),designs:clone(store.designs.filter(d=>d.planId===PLAN.id)),catalog:clone(store.custom||[])});P.unpack(payload);
  const image=include3D?window.View3D?.image():null,table=(headers,rows)=>`<table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
  const rooms=ROOMS.map(r=>[state.rooms[r.id].name,useName(D.inferUse(r,state.rooms[r.id])),area(r.poly).toFixed(2)+(r.counted===false?' *':''),nm(MATS[state.rooms[r.id].mat].name)]),purchase=P.procurement(plan,state,priceOf),items=purchase.items.map(f=>[nm(f.name),f.brand,f.model,`${f.w} × ${f.d} × ${f.h??'待录入'}`,f.quantity,P.purchaseStates[f.status],P.purchaseMoney(f.price)+(f.estimated?'（参考）':''),P.purchaseMoney(f.total)]);
  const sourcing=purchase.items.map(f=>[nm(f.name),f.rooms.join('、'),f.priceDate||'未记录',f.sourceUrl||'未记录',f.note]);
  const costs=P.extraCosts(state.renovation||[],q).items.map(r=>[r.name,r.quantity.toFixed(2)+' '+r.unit,yen(r.price),yen(r.total)]);
  const openings=P.openingSchedule(plan,state).map(o=>[o.name,o.type,o.width,o.height,o.sill,o.depth??'—']);
  const findings=P.review(plan,state).map(v=>[v.name,v.message,v.ignored?'已核对并忽略':'待核对']);
  plan.rooms.filter(r=>r.counted!==false&&D.inferUse(r,state.rooms[r.id])==='unassigned').forEach(r=>findings.push([r.name,'房间用途未分类','待设置']));
  const reviewSection=`<h2>设计核对记录</h2><p class="note">候选间隙阈值 ${state.spaceThreshold||800} mm。此记录按导出时的几何生成；候选狭窄间隙不代表完整通行路径判断。</p>${findings.length?table(['对象','事项','状态'],findings):'<p>本轮自动检查未发现待核对事项。</p>'}`;
  const embedded=JSON.stringify(payload).replace(/</g,String.fromCharCode(92)+'u003c');
  return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>body{font:15px/1.7 system-ui,sans-serif;color:#302923;background:#f6f2eb;margin:0}main{max-width:1050px;margin:auto;padding:28px;background:white}h1,h2{line-height:1.3}h2{margin-top:32px}small,p.note{color:#766c60}button{padding:10px 16px;border:1px solid #ddd0bf;border-radius:8px;background:#fff7ed;cursor:pointer;margin-right:8px}svg,img{max-width:100%;height:auto}svg{background:#fffaf4}table{width:100%;border-collapse:collapse;overflow-wrap:anywhere}th,td{padding:9px;text-align:left;border-bottom:1px solid #e9e2d8}th{background:#f6f2eb}.total{font-size:22px;font-weight:700;color:#dd551e}.actions{margin:20px 0}@media print{body{background:white}main{padding:0}.actions{display:none}h2{break-after:avoid}tr,img{break-inside:avoid}svg{max-height:650px}}</style><main><h1>${esc(title)}</h1><p>${esc(PLAN.name)} · 套内使用面积 ${q.net.toFixed(2)} m² · 尺寸单位 mm</p><p class="note">${esc(note).replace(/\n/g,'<br>')}</p><div class="actions"><button onclick="window.print()">打印／另存为 PDF</button><button id="project-download">下载可编辑项目</button><button id="drawing-download">下载平面 SVG</button></div><h2>平面布置</h2>${floorplanSVG(drawingOptions)}${image?`<h2>三维效果</h2><img src="${image}" alt="当前三维视角">`:''}<h2>房间与材料</h2>${table(['房间','用途','面积 m²','地面材料'],rooms)}<p class="note">* 飘窗台单独统计，不计入套内使用面积。</p><h2>门窗尺寸清单</h2>${table(['名称','类型','洞口宽／三面宽 mm','净高 mm','窗台高 mm','外凸进深 mm'],openings)}<p class="note">自定义飘窗宽为原墙洞口宽，内置三面飘窗列出各面图纸宽度。门高按当前模型预设估算，窗高采用已编辑尺寸。</p><h2>家具清单</h2>${table(['名称','品牌','型号','尺寸 mm','数量','采购状态','单价','小计'],items)}<h2>采购资料</h2>${table(['名称','所在房间','价格日期','来源链接','采购备注'],sourcing)}<p class="note">采购状态用于进度记录，所有条目仍计入家具预算；参考价及未录入高度需核对实际产品。</p>${reviewSection}<h2>预算汇总</h2>${table(['项目','金额'],[['地面（含 5% 损耗）',yen(stats.floor)],['墙面乳胶漆（含 10% 损耗）',yen(stats.paint*1.1*28)],['家具家电',yen(stats.furniture)],['装修工程',yen(stats.extra)]])}<p class="total">合计 ${yen(stats.total)}</p>${costs.length?`<h2>装修工程明细</h2>${table(['项目','工程量','单价','金额'],costs)}`:''}<p class="note">预算为按录入数据计算的参考估价。项目文件可在 Furnish 户型库加载并继续编辑。</p><script type="application/json" id="project-data">${embedded}</script><script>document.getElementById('drawing-download').onclick=()=>{const source=new XMLSerializer().serializeToString(document.getElementById('report-plan')),blob=new Blob([source],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='floorplan.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};document.getElementById('project-download').onclick=()=>{const blob=new Blob([document.getElementById('project-data').textContent],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='design.furnish.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};<\/script></main></html>`;
 }
 function delivery(){const ready=!!window.View3D?.image();openDialog({title:tr('导出方案成果','Export design report'),wide:true,body:`<p>${tr('导出可离线打开的 HTML，包含平面布置、房间材料、家具清单、完整预算及可编辑项目。打开后可打印为 PDF。','Export an offline HTML report with plan, materials, items, costs and an editable project; print it to PDF.')}</p><div class="project-grid"><label>${tr('成果名称','Report title')}<input id="delivery-title" maxlength="100" value="${esc(PLAN.name+' · 装修方案')}"></label><label>${tr('方案说明','Design notes')}<textarea id="delivery-note" maxlength="1000" rows="4">${esc(state.designNote||'')}</textarea></label></div><div class="chiprow" style="margin:14px 0"><label class="btn"><input type="checkbox" id="delivery-dims" checked> ${tr('包含图纸尺寸链','Include dimension chains')}</label><label class="btn"><input type="checkbox" id="delivery-measures" checked> ${tr('包含已保存测量线','Include saved measurements')}</label><label class="btn"><input type="checkbox" id="delivery-notes" checked> ${tr('包含文字标注','Include notes')}</label></div><p><label><input type="checkbox" id="delivery-3d" ${ready?'checked':'disabled'}> ${tr('附上当前三维视角','Include current 3D view')}</label></p>${ready?'':`<p class="project-note">${tr('先切换到 3D 并调整视角，再打开此窗口即可附上效果图。','Visit 3D and choose a view before exporting to include an image.')}</p>`}<p id="delivery-error" class="project-error" role="alert"></p>`,actions:[{label:tr('取消','Cancel')},{label:tr('导出成果 HTML','Export HTML'),cls:'primary',fn:()=>{try{const title=$('#delivery-title').value.trim()||PLAN.name;const html=reportHTML(title,$('#delivery-note').value,$('#delivery-3d').checked,{dimensions:$('#delivery-dims').checked,measurements:$('#delivery-measures').checked,notes:$('#delivery-notes').checked});download(title.replace(/[\\/:*?"<>|]/g,'_')+'.html',new Blob([html],{type:'text/html;charset=utf-8'}));return true;}catch(e){$('#delivery-error').textContent=e.message;return false;}}}]});}
 window.FurnishDesignUI={workflow,roomUses,placementPanel,groupPlacementPanel,bindPlacement,clearPlacementGuide,delivery,reportHTML,designs,editDesign,recovery,previewRecovery};
 $('#saveDesign').onclick=()=>editDesign('create');
 $('#projectWorkspace').onclick=workflow;
 const recoveryButton=document.createElement('button');recoveryButton.className='btn';recoveryButton.id='recoveryPoints';recoveryButton.textContent=tr('恢复记录','Recovery points');$('#saveDesign').after(recoveryButton);recoveryButton.onclick=()=>{recovery();$('#fileMenu').open=false;};
 const originalOpen=FurnishWorkspace.open;FurnishWorkspace.open=tab=>{originalOpen(tab);if(tab==='compare'){$('#project-content').insertAdjacentHTML('afterbegin',`<p><button class="btn" id="cmp-manage">${tr('管理命名方案','Manage saved designs')}</button></p>`);$('#cmp-manage').onclick=designs;}};
 $('#vSelection').onclick=()=>window.View3D?.focusSelection();
 renderPanel();
})();
