/* Search specifications and preview a catalog replacement before committing. */
(function(){
 const P=FurnishProject,D=FurnishDesign;
 const source=it=>({...((store.custom||[]).find(c=>c.id===it[7])||{}),type:it[0],name:it[1],w:it[2],d:it[3],color:it[4],price:it[5],h:it[6],...(it[0]==='curtain'?{curtainStyle:it[8]||'double'}:{})});
 function matches(it,q,w,d){const c=source(it);return [c.name,nm(c.name),c.brand,c.model].join(' ').toLowerCase().includes(q.toLowerCase())&&(!w||c.w<=w)&&(!d||c.d<=d);}
 $('#lib').insertAdjacentHTML('beforebegin','<div class="form" style="padding:8px"><label>最大宽 mm<input id="catalog-max-w" type="number" min="50" placeholder="不限"></label><label>最大深 mm<input id="catalog-max-d" type="number" min="50" placeholder="不限"></label></div>');
 for(const id of ['catalog-max-w','catalog-max-d'])$('#'+id).oninput=buildLib;
 function replacement(){const f=selItems()[0];if(!f)return toast('请先选择一件家具');if(f.locked)return toast('请先解锁家具');let candidate=null;
  openDialog({title:'查找并替换家具',wide:true,body:`<p>替换「${esc(f.name)}」，保留编号、旋转及尺寸调整基准；品牌规格和采购进度使用新产品。</p><div class="project-grid"><label>名称／品牌／型号<input id="replace-query"></label><label>最大宽 mm<input id="replace-w" type="number" min="50"></label><label>最大深 mm<input id="replace-d" type="number" min="50"></label></div><div id="replace-results" style="max-height:240px;overflow:auto;margin-top:12px;overflow-wrap:anywhere"></div><div id="replace-preview" role="status"></div>`,actions:[{label:'取消'},{label:'应用替换',cls:'primary',fn:()=>{try{if(!candidate)throw Error('请先选择候选家具');const next=D.replaceFurniture(getF(f.id),candidate);P.validateWork({furniture:[next]});mutate(()=>{Object.assign(getF(f.id),next);for(const key of ['price','h','obj','catalogId','catalogSnapshot','catalogDetached','curtainStyle'])if(!Object.hasOwn(next,key))delete getF(f.id)[key];});renderAll();return true;}catch(e){$('#replace-preview').textContent=e.message;return false;}}}],onOpen:()=>{
   const show=()=>{candidate=null;$('#replace-preview').textContent='';const rows=libAll().flatMap(c=>c.items).filter(it=>matches(it,$('#replace-query').value,Number($('#replace-w').value),Number($('#replace-d').value)));$('#replace-results').innerHTML=rows.map((it,i)=>`<button class="btn" data-replacement="${i}" style="margin:4px;white-space:normal;max-width:calc(100% - 8px);overflow-wrap:anywhere">${esc(it[1])} · ${it[2]}×${it[3]} mm · ${esc([source(it).brand,source(it).model].filter(Boolean).join(' '))}</button>`).join('')||'<p>没有匹配家具。</p>';document.querySelectorAll('[data-replacement]').forEach(b=>b.onclick=()=>{candidate=source(rows[+b.dataset.replacement]);try{const next=D.replaceFurniture(f,candidate),issues=P.spaceCheck(P.effectivePlan(PLAN,state),state.furniture.map(v=>v.id===f.id?next:v),{focusId:f.id,scanPassages:false});$('#replace-preview').innerHTML=`<p>${esc(f.name)} → ${esc(candidate.name)} · ${next.w}×${next.d} mm · ${P.purchaseMoney(candidate.price)}</p>${issues.map(v=>`<p class="project-error">${esc(v.message)}</p>`).join('')||'<p>未发现占地冲突。</p>'}`;}catch(e){candidate=null;$('#replace-preview').textContent=e.message;}});};for(const id of ['replace-query','replace-w','replace-d'])$('#'+id).oninput=show;show();
  }});
 }
 window.FurnishCatalog={matches,replacement};document.addEventListener('click',e=>{if(e.target.closest('#replace-furniture'))replacement();});
})();
