/* Procurement progress uses placed furniture as the source of truth. */
(function(){
 'use strict';const P=FurnishProject;
 const dimensions=f=>`${f.w} × ${f.d} × ${f.h??'待录入'} mm`;
 function list(){return P.procurement(P.effectivePlan(PLAN,state),state,priceOf);}
 function exportList(){const purchase=list(),headers=['名称','品牌','型号','宽 mm','深 mm','高 mm','数量','所在房间','单价','价格依据','小计','采购状态','价格日期','来源链接','采购备注'],rows=purchase.items.map(f=>[nm(f.name),f.brand,f.model,f.w,f.d,f.h??'待录入',f.quantity,f.rooms.join('、'),Math.round(f.price),f.estimated?'参考价':'录入价',Math.round(f.total),P.purchaseStates[f.status],f.priceDate,f.sourceUrl,f.note]);download('采购清单-'+PLAN.name+'.csv',new Blob([P.csv([headers,...rows,[],['合计','','','','','','','','','',Math.round(purchase.total)]])],{type:'text/csv;charset=utf-8'}));}
 function editGroup(item,filter){
  const shownPrice=Number.isFinite(item.price)?String(Math.round(item.price)):'',fields=[['brand','品牌',item.brand],['model','型号',item.model],['priceDate','价格日期',item.priceDate],['sourceUrl','购买／价格来源链接',item.sourceUrl]];
  const edited=new Set();let priceEdited=false;openDialog({title:tr('编辑本组采购资料','Edit group purchase details'),body:`<p><b>${esc(nm(item.name))}</b> · ${item.quantity} 件 · ${item.w===undefined||item.d===undefined?'多种尺寸':dimensions(item)}<br>${esc(item.rooms.join('、'))}</p><p class="project-note">本组家具统一更新资料；位置和尺寸可在画布逐件编辑。未更改单价时保留原始价格精度和价格依据。</p><div class="project-grid">${fields.map(([key,label,value])=>`<label>${label}<input id="purchase-group-${key}" type="${key==='priceDate'?'date':key==='sourceUrl'?'url':'text'}" maxlength="${key==='name'?80:500}" value="${esc(value||'')}" placeholder="${value===undefined?'各件不同，留空保留':''}"></label>`).join('')}<label>单价 ¥（当前${item.estimated===undefined?'各件不同':item.estimated?'参考价':'录入价'}）<input id="purchase-group-price" type="number" min="0" max="10000000" step="1" value="${shownPrice}"></label></div><p><label><input id="purchase-group-reference" type="checkbox">恢复本组家具的来源参考价</label></p><p id="purchase-group-error" class="project-error" role="alert"></p>`,actions:[{label:tr('返回清单','Back to list'),fn:()=>{open(filter);return false;}},{label:tr('保存本组资料','Save group details'),cls:'primary',fn:()=>{try{
   const patch={};for(const [key,,before] of fields){const value=$('#purchase-group-'+key).value.trim();if(edited.has(key)||value!==(before||''))patch[key]=value;}
   const reference=$('#purchase-group-reference').checked,priceText=$('#purchase-group-price').value.trim();if(reference)patch.price=null;else if(priceEdited||priceText!==shownPrice){const price=Number(priceText);if(!priceText||!Number.isFinite(price)||price<0||price>1e7)throw Error('单价须为 0–10000000 元');patch.price=Math.round(price);}
   if(Object.keys(patch).length){const next=P.updatePurchaseGroup(state,item.ids,patch);mutate(()=>state.furniture=next.furniture);}open(filter);toast(tr('本组采购资料已保存，可撤销。','Group details saved; undo is available.'));return false;
  }catch(e){$('#purchase-group-error').textContent=e.message;return false;}}}],onOpen:()=>{for(const [key] of fields)$('#purchase-group-'+key).oninput=()=>edited.add(key);$('#purchase-group-price').oninput=()=>priceEdited=true;$('#purchase-group-reference').onchange=e=>$('#purchase-group-price').disabled=e.target.checked;}});
 }
 function open(filter='all'){
  const purchase=list(),items=purchase.items.filter(f=>filter==='all'||f.status===filter),count=items.reduce((n,f)=>n+f.quantity,0);
  openDialog({title:tr('家具采购清单','Furniture purchase list'),wide:true,body:`<p>${tr('来自当前画布的家具，按尺寸、品牌、型号、价格及状态区分。同一组状态与备注同步修改，支持撤销。采购状态用于进度记录，所有条目仍计入预算。','Based on the current furniture, grouped by specifications, brand, model, price and status. Group edits are undoable. All statuses remain included in the budget.')}</p><div class="project-grid">${Object.entries(P.purchaseStates).map(([id,name])=>`<div><b>${name}</b><p>${P.purchaseMoney(purchase.totals[id])}</p></div>`).join('')}</div><p class="project-note">${purchase.estimated} 件使用参考价 · ${purchase.missingHeight} 件尚未录入实际高度，可在家具资料中核对。</p><div style="display:flex;flex-wrap:wrap;align-items:center;gap:10px"><label>筛选 <select id="purchase-filter"><option value="all">全部</option>${Object.entries(P.purchaseStates).map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}</select></label><button class="btn" id="purchase-export">${tr('导出完整采购 CSV','Export complete purchase CSV')}</button><span>${count} 件 · ${items.length} 组</span></div><div style="display:grid;gap:12px;margin-top:14px">${items.map((f,i)=>`<article data-purchase-row="${i}" style="border:1px solid var(--line);border-radius:12px;padding:14px;overflow-wrap:anywhere"><b>${esc(nm(f.name))}</b> · ${f.quantity} 件<p>${esc([f.brand,f.model].filter(Boolean).join(' ')||'品牌／型号未记录')}<br>${dimensions(f)} · ${esc(f.rooms.join('、'))}<br>单价 ${P.purchaseMoney(f.price)}${f.estimated?'（参考）':''} · 小计 ${P.purchaseMoney(f.total)} · 价格日期 ${esc(f.priceDate||'未记录')}</p><div class="project-grid"><label>采购状态<select data-purchase-status="${i}" aria-label="采购状态 ${esc(nm(f.name))}">${Object.entries(P.purchaseStates).map(([id,name])=>`<option value="${id}" ${f.status===id?'selected':''}>${name}</option>`).join('')}</select></label><label>采购备注<textarea data-purchase-note="${i}" maxlength="500" rows="2" aria-label="采购备注 ${esc(nm(f.name))}">${esc(f.note)}</textarea></label></div><p data-purchase-error="${i}" class="project-error" role="alert"></p><p style="display:flex;flex-wrap:wrap;gap:8px"><button class="btn primary" data-purchase-apply="${i}">保存本组采购信息</button><button class="btn" data-purchase-group-edit="${i}">编辑本组资料</button><button class="btn" data-purchase-edit="${i}">编辑首件尺寸／模型</button><button class="btn" data-purchase-locate="${i}">定位首件</button>${/^https?:\/\//i.test(f.sourceUrl)?`<a class="btn" href="${esc(f.sourceUrl)}" target="_blank" rel="noopener noreferrer">价格来源</a>`:''}</p></article>`).join('')||'<p>当前筛选下没有条目。</p>'}</div>`,actions:[{label:tr('关闭','Close')}],onOpen:()=>{
   $('#purchase-filter').value=filter;$('#purchase-filter').onchange=e=>open(e.target.value);$('#purchase-export').onclick=exportList;
   document.querySelectorAll('[data-purchase-group-edit]').forEach(button=>button.onclick=()=>editGroup(items[Number(button.dataset.purchaseGroupEdit)],filter));
   document.querySelectorAll('[data-purchase-apply]').forEach(input=>input.onclick=()=>{const index=Number(input.dataset.purchaseApply),f=items[index],row=input.closest('[data-purchase-row]'),status=row.querySelector('[data-purchase-status]').value,note=row.querySelector('[data-purchase-note]').value.trim();try{const next=P.updatePurchaseGroup(state,f.ids,{purchaseStatus:status,purchaseNote:note});mutate(()=>state.furniture=next.furniture);open(filter);}catch(e){row.querySelector('[data-purchase-error]').textContent=e.message;}});
   document.querySelectorAll('[data-purchase-edit],[data-purchase-locate]').forEach(button=>button.onclick=()=>{const f=items[Number(button.dataset.purchaseEdit??button.dataset.purchaseLocate)];closeDialog();if(button.dataset.purchaseEdit!==undefined){select({kind:'furn',id:f.ids[0]});FurnishWorkspace.open('products');}else focusItem(f.ids[0]);});
  }});
 }
 function editSelection(){const ids=selIds(),furniture=state.furniture.filter(f=>ids.includes(f.id));if(!furniture.length)return toast('请先选择家具');const common=fn=>furniture.every(f=>fn(f)===fn(furniture[0]))?fn(furniture[0]):undefined,item={ids,quantity:ids.length,name:common(f=>f.name)||'选中家具',rooms:[...new Set(list().items.filter(g=>g.ids.some(id=>ids.includes(id))).flatMap(g=>g.rooms))],price:common(priceOf),estimated:common(f=>f.price===undefined)};for(const key of ['brand','model','priceDate','sourceUrl','w','d','h'])item[key]=common(f=>f[key]??(['w','d','h'].includes(key)?undefined:''));editGroup(item,'all');}
 window.FurnishPurchases={open,exportList,list,editSelection};document.addEventListener('click',e=>{if(e.target.closest('#selection-product-details'))editSelection();});const previous=FurnishWorkspace.open;FurnishWorkspace.open=tab=>{if(tab==='purchases')return open();previous(tab);if(tab==='products'){$('#project-content').insertAdjacentHTML('afterbegin','<p><button class="btn" id="products-purchases">查看采购清单</button></p>');$('#products-purchases').onclick=()=>open();}};
 const button=document.createElement('button');button.id='purchaseList';button.className='btn';button.textContent=tr('采购清单','Purchase list');$('#recoveryPoints').after(button);button.onclick=()=>{$('#fileMenu').open=false;open();};
})();
