/* Workspace for structure/design differences, comparison, costs, assets and products. */
(function(){
 'use strict';
 const P=FurnishProject,clone=v=>JSON.parse(JSON.stringify(v)),t=(zh,en)=>tr(zh,en);

 const button=document.createElement('button');button.className='btn outline';button.id='projectWorkspace';button.textContent=t('项目工作台','Project workspace');$('#tracePlan').after(button);button.onclick=()=>open('structure');
 function currentArchitecture(){return state.architecture?P.architecture(state.architecture):null;}
 function applyDraft(draft,clearWindow){const a=currentArchitecture();if(a.phase==='design')P.assertStructure(a.baseline,draft);const plan=FurnishDraft.build(draft),settings=P.remapRooms(ROOMS,plan.rooms,state.rooms);mutate(()=>{state.architecture={...a,draft};state.rooms=settings;state.demolished=[];state.open=P.remapOpenings(PLAN,plan,state.open);if(clearWindow)plan.winRefs.forEach((id,i)=>{if(id===clearWindow)delete state.open.w[i];});});}
 function demolish(id){try{const a=currentArchitecture();if(a.phase!=='design')return toast(t('请先录入并确认原始结构，再开始拆改。','Confirm the original structure before demolition.'));const wall=a.draft.walls.find(w=>w.id===PLAN.wallRefs?.[Number(id.slice(1))]);if(!wall)return;if(wall.kind!=='n')return toast(t('承重墙和外墙已锁定，不可拆改。','Bearing and exterior walls are locked.'));const next=clone(a.draft);next.walls=next.walls.filter(w=>w.id!==wall.id);next.openings=next.openings.filter(o=>o.wall!==wall.id);applyDraft(next);toast(t('已拆除整段非承重墙，房间和面积已重新计算；可撤销恢复。','Partition removed; rooms and area recalculated. Undo to restore.'));}catch(e){toast(t('拆改未应用：','Demolition not applied: ')+e.message);}}
 svg.addEventListener('pointerdown',e=>{const el=e.target.closest('[data-restore-wall]');if(!el||ui.tool!=='demolish')return;e.preventDefault();e.stopImmediatePropagation();try{const a=currentArchitecture(),w=a.baseline.walls.find(w=>w.id===el.dataset.restoreWall),next=clone(a.draft);if(next.walls.some(v=>v.id===w.id))throw Error(t('墙体已被移动，请在墙属性中恢复位置。','Moved wall: restore its position in wall properties.'));next.walls.push(clone(w));next.openings.push(...clone(a.baseline.openings.filter(o=>o.wall===w.id)));applyDraft(next);}catch(err){toast(err.message);}},true);
 function afterRender(){let g=$('#gRenovation');if(!g){g=document.createElementNS('http://www.w3.org/2000/svg','g');g.id='gRenovation';$('#gWalls').after(g);}g.innerHTML='';if(!state.architecture?.baseline)return;const a=state.architecture,c=P.changes(a.baseline,a.draft);g.style.pointerEvents=ui.tool==='demolish'?'all':'none';g.innerHTML+=c.removed.map(w=>{const r=FurnishDraft.wallRect(w,a.baseline.scale);return `<rect data-restore-wall="${esc(w.id)}" x="${r[0]}" y="${r[1]}" width="${r[2]-r[0]}" height="${r[3]-r[1]}" fill="rgba(210,70,50,.12)" stroke="#c64a36" stroke-width="1.5" stroke-dasharray="6 4" vector-effect="non-scaling-stroke"><title>${t('拆除墙体：拆改工具下点击可恢复','Removed wall: click with demolition tool to restore')}</title></rect>`;}).join('')+c.added.map(w=>{const r=FurnishDraft.wallRect(w,a.draft.scale);return `<rect x="${r[0]}" y="${r[1]}" width="${r[2]-r[0]}" height="${r[3]-r[1]}" fill="none" stroke="#17806c" stroke-width="2" vector-effect="non-scaling-stroke" pointer-events="none"/>`;}).join('');}
 function planFor(work){return P.effectivePlan(PLAN,work);}
 function summary(work){const b=P.estimate(planFor(work),work,MATS,priceOf);return {...b,rooms:b.counted.length,paint:b.paintArea,extra:b.renovation};}
 const nav=[['structure','原始结构／拆改','Structure / changes'],['compare','方案比较','Compare'],['backup','项目备份','Backup'],['space','使用空间检查','Space checks'],['budget','装修工程预算','Renovation costs'],['products','品牌家具／模型','Products / models']];
 function open(tab='structure'){
  $('#fileMenu').open=false;openDialog({title:t('项目工作台','Project workspace'),wide:true,body:`<nav class="project-nav">${nav.map(([id,zh,en])=>`<button class="btn ${id===tab?'on':''}" data-project-tab="${id}">${t(zh,en)}</button>`).join('')}</nav><div id="project-content"></div><p id="project-error" class="project-error" role="alert"></p>`,actions:[{label:t('关闭','Close')}],onOpen:()=>{document.querySelectorAll('[data-project-tab]').forEach(b=>b.onclick=()=>open(b.dataset.projectTab));try{({structure,compare,backup,space,budget:costs,products})[tab]();}catch(e){error(e);}}});
 }
 const content=html=>$('#project-content').innerHTML=html,error=e=>$('#project-error').textContent=e.message;
 const field=(id,name,value,type='text',more='')=>`<label>${name}<input id="${id}" type="${type}" value="${esc(value??'')}" ${more}></label>`;
 function structure(){const a=currentArchitecture();if(!a){content(`<p>${t('当前为内置示例户型。原始结构和真实拆改适用于自定义户型，请先导入你的 DXF 或图片。','Import your DXF or image to work with an editable original structure.')}</p><button class="btn primary" id="pr-edit">${t('导入／录入自己的户型','Import your floor plan')}</button>`);$('#pr-edit').onclick=()=>{closeDialog();$('#tracePlan').click();};return;}
  const current=FurnishDraft.build(a.draft),base=a.baseline?FurnishDraft.build(a.baseline):current,c=a.baseline?P.changes(a.baseline,a.draft):{removed:[],added:[]},q=P.quantities(current,a);
  content(`<p><b>${a.phase==='survey'?t('阶段 1：原始结构录入（未锁定）','Stage 1: original survey (unlocked)'):t('阶段 2：装修设计（结构已锁定）','Stage 2: design (structure locked)')}</b></p><p>${t('先补录已有门窗、核对每段墙的类型与尺寸，再确认原始结构。装修阶段修改非承重墙；红色虚线为拆除，绿色为新增／移动。','Record existing openings and verify wall types before confirmation. Red = removed; green = added/moved.')}</p><div class="project-grid"><div><h4>${t('原始户型','Original')}</h4>${planThumb(base)}</div><div><h4>${t('当前方案','Current design')}</h4>${planThumb(current)}</div></div><p>${t(`当前 ${q.rooms} 个房间，净面积 ${q.net.toFixed(2)} m²；拆除 ${q.removed.toFixed(2)} m，新建 ${q.added.toFixed(2)} m。`,`Current: ${q.rooms} rooms, ${q.net.toFixed(2)} m²; removed ${q.removed.toFixed(2)} m, added ${q.added.toFixed(2)} m.`)}</p><p>${t('主界面拆改工具会移除完整中心线墙段并重算房间；红色拆除墙上再次点击可恢复。','Demolition removes a complete wall segment and recalculates rooms; click the red removed wall to restore.')}</p><button class="btn primary" id="pr-edit">${t('录入／编辑墙体与已有门窗','Edit walls and existing openings')}</button><button class="btn" id="pr-copy-survey">${t('复制原始户型重新核对','Copy original for a new survey')}</button><button class="btn" id="pr-diff">${t('下载拆改对比 SVG','Download change drawing SVG')}</button>`);
  document.querySelectorAll('#project-content svg').forEach(s=>s.classList.add('project-thumb'));$('#pr-edit').onclick=()=>{closeDialog();$('#tracePlan').click();};$('#pr-copy-survey').onclick=()=>{const draft=clone(a.baseline||a.draft);draft.id='custom_'+uid();draft.name=draft.name.slice(0,65)+t(' · 重新核对',' · New survey');const plan=FurnishDraft.build(draft);store.customPlans.push(draft);PLANS.push(plan);store.work[plan.id]=freshWork(plan);store.work[plan.id].architecture={draft,phase:'survey'};closeDialog();setPlan(plan.id);$('#tracePlan').click();};$('#pr-diff').onclick=()=>{const b=current.bounds,wall=(w,d,color,dashed)=>{const r=FurnishDraft.wallRect(w,d.scale,d.walls);return `<rect x="${r[0]}" y="${r[1]}" width="${r[2]-r[0]}" height="${r[3]-r[1]}" fill="${color}" ${dashed?'stroke="#c64a36" stroke-dasharray="80 50" stroke-width="20"':''}/>`;};const drawing=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${b.x} ${b.y} ${b.w} ${b.h}"><title>${esc(a.draft.name)} · 红：拆除；绿：新建；灰：保留 · 单位 mm</title>${a.draft.walls.map(w=>wall(w,a.draft,'#aaa',false)).join('')}${c.removed.map(w=>wall(w,a.baseline,'#f4d4cf',true)).join('')}${c.added.map(w=>wall(w,a.draft,'#168269',false)).join('')}</svg>`;download('拆改对比.svg',new Blob([drawing],{type:'image/svg+xml'}));};
 }
 function compare(){const designs=store.designs.filter(d=>d.planId===PLAN.id),choices=[{id:'current',name:t('当前工作方案','Current work'),work:state},...designs];content(`<p>${t('比较同一原始户型的布局、净面积、拆改量和完整预算。保存方案会保留独立墙体、家具与工程费用。','Compare layout, area, wall changes and total costs; each saved design has independent geometry and costs.')}</p><div class="project-grid">${['a','b'].map((id,i)=>`<label>${t('方案','Design')} ${id.toUpperCase()}<select id="cmp-${id}">${choices.map((d,j)=>`<option value="${esc(d.id)}" ${j===Math.min(i,choices.length-1)?'selected':''}>${esc(d.name)}</option>`).join('')}</select></label>`).join('')}</div><div id="cmp-result"></div><div class="project-grid" style="margin-top:15px">${field('cmp-name',t('保存当前方案名称','Save current design name'),'方案 '+(designs.length+1))}${field('cmp-note',t('方案备注（随方案备份）','Design notes (included in backup)'),state.designNote||'','text','maxlength="500"')}<button class="btn primary" id="cmp-save">${t('保存当前方案','Save current design')}</button></div>`);
  const show=()=>{const pair=['a','b'].map(id=>choices.find(d=>d.id===$('#cmp-'+id).value)),stats=pair.map(d=>summary(d.work)),keys=[['rooms','房间数'],['net','净面积 m²'],['removed','拆墙 m'],['added','新建墙 m'],['furniture','家具预算 ¥'],['extra','工程预算 ¥'],['total','总预算 ¥']];$('#cmp-result').innerHTML=`<div class="project-grid">${pair.map(d=>`<div><h4>${esc(d.name)}</h4>${planThumb(planFor(d.work))}<p>${d.work.furniture.length} ${t('件家具','items')} · ${esc(d.work.designNote||t('无备注','No notes'))}</p></div>`).join('')}</div><table class="project-table"><thead><tr><th>${t('指标','Metric')}</th><th>A</th><th>B</th><th>B − A</th></tr></thead><tbody>${keys.map(([k,n])=>`<tr><td>${n}</td><td>${(['furniture','extra','total'].includes(k)?Math.round(stats[0][k]).toLocaleString():stats[0][k].toFixed(2))}</td><td>${(['furniture','extra','total'].includes(k)?Math.round(stats[1][k]).toLocaleString():stats[1][k].toFixed(2))}</td><td style="font-weight:700;color:${Math.abs(stats[1][k]-stats[0][k])>.005?'var(--accent)':'inherit'}">${(['furniture','extra','total'].includes(k)?Math.round(stats[1][k]-stats[0][k]).toLocaleString():(stats[1][k]-stats[0][k]).toFixed(2))}</td></tr>`).join('')}</tbody></table>`;const addFurniture=(s,d)=>{const b=planFor(d.work).bounds;s.classList.add('project-thumb');if(d.work.architecture?.baseline){const a=d.work.architecture,c=P.changes(a.baseline,a.draft);s.innerHTML+=[...c.removed.map(w=>({w,d:a.baseline,color:'#c64a36',dash:'80 50'})),...c.added.map(w=>({w,d:a.draft,color:'#17806c',dash:''}))].map(({w,d,color,dash})=>{const r=FurnishDraft.wallRect(w,d.scale,d.walls);return `<rect x="${r[0]}" y="${r[1]}" width="${r[2]-r[0]}" height="${r[3]-r[1]}" fill="none" stroke="${color}" stroke-width="25" stroke-dasharray="${dash}"/>`;}).join('');}s.innerHTML+=d.work.furniture.map(f=>`<polygon points="${P.polygon(f).map(p=>p.join(',')).join(' ')}" fill="${/^#[0-9a-f]{3,8}$/i.test(f.color)?f.color:'#cda'}" stroke="#685c4f" stroke-width="15"/>`).join('');};const drawings=[...document.querySelectorAll('#cmp-result svg')];drawings.forEach((s,i)=>addFurniture(s,pair[i]));
      const boxes=drawings.map(s=>s.getAttribute('viewBox').split(' ').map(Number)),left=Math.min(...boxes.map(b=>b[0])),top=Math.min(...boxes.map(b=>b[1])),right=Math.max(...boxes.map(b=>b[0]+b[2])),bottom=Math.max(...boxes.map(b=>b[1]+b[3]));let view=[left,top,right-left,bottom-top];const sync=()=>drawings.forEach(s=>s.setAttribute('viewBox',view.join(' ')));sync();
      drawings.forEach(s=>{s.style.touchAction='none';s.setAttribute('aria-hidden','false');s.setAttribute('aria-label','方案对比：滚轮同步缩放，拖动同步平移，双击复位');s.onwheel=e=>{e.preventDefault();const factor=e.deltaY>0?1.15:1/1.15;if(view[2]*factor<100||view[2]*factor>200000)return;view=[view[0]+view[2]*(1-factor)/2,view[1]+view[3]*(1-factor)/2,view[2]*factor,view[3]*factor];sync();};let drag=null;s.onpointerdown=e=>{drag=[e.clientX,e.clientY,...view];s.setPointerCapture(e.pointerId);};s.onpointermove=e=>{if(!drag)return;const r=s.getBoundingClientRect(),scale=Math.max(view[2]/r.width,view[3]/r.height);view=[drag[2]-(e.clientX-drag[0])*scale,drag[3]-(e.clientY-drag[1])*scale,drag[4],drag[5]];sync();};s.onpointerup=s.onpointercancel=()=>drag=null;s.ondblclick=()=>{view=[left,top,right-left,bottom-top];sync();};});
      $('#cmp-result').insertAdjacentHTML('afterbegin','<p class="project-note">滚轮同步缩放 · 拖动同步平移 · 双击复位。承重：黑色／点线；外墙：灰色／长虚线；非承重：棕色／实线；拆除：红色虚线；新增／移动：绿色轮廓。</p>');};$('#cmp-a').onchange=$('#cmp-b').onchange=show;show();$('#cmp-save').onclick=()=>{const name=$('#cmp-name').value.trim();if(designs.length>=100)return error(Error('每个户型最多 100 份命名方案'));if(!name||name.length>80)return error(Error(t('名称须为 1–80 个字符','Name must be 1–80 characters')));try{const note=$('#cmp-note').value.trim().slice(0,500),next=FurnishDesign.manageDesign(store.designs,PLAN.id,'create',{name,work:state,note});mutate(()=>state.designNote=note);store.designs=next;save();renderDesigns();open('compare');}catch(e){error(e);}};
 }
 function backup(){content(`<p>${t('项目文件包含当前户型、原始结构、所有命名方案、工程费用、品牌家具库和附加源文件。版本号与完整性校验用于发现损坏；旧版方案 JSON 也可迁移导入。','Back up geometry, original structure, named designs, costs, product catalog and attached source files. Versioning and integrity checks detect damage; legacy plan JSON is accepted.')}</p><button class="btn primary" id="pr-export">${t('导出完整项目','Export full project')}</button><button class="btn" id="pr-import">${t('导入完整项目／旧方案','Import project / legacy plan')}</button><input id="pr-file" type="file" accept=".json,.furnish" hidden><h4>${t('附加原始图纸／报价文件','Attach source drawings / quotes')}</h4><p class="project-note">${t('每个附件上限 2 MB，最多 5 个。附件保存在本机并随项目导出；图片底图已包含在户型数据中。','Up to five attachments, 2 MB each. Stored locally and exported; image references are already embedded.')}</p><button class="btn" id="pr-attach">${t('添加源文件附件','Attach source file')}</button><input id="pr-asset" type="file" hidden><div id="pr-assets"></div>`);
  const list=()=>{$('#pr-assets').innerHTML=(state.assets||[]).map((a,i)=>`<p>${esc(a.name)} <button class="btn" data-asset-download="${i}">${t('下载','Download')}</button><button class="btn" data-asset-delete="${i}">${t('移除','Remove')}</button></p>`).join('');document.querySelectorAll('[data-asset-download]').forEach(b=>b.onclick=()=>{const a=state.assets[+b.dataset.assetDownload],bytes=Uint8Array.from(atob(a.data),c=>c.charCodeAt(0));download(a.name,new Blob([bytes],{type:'application/octet-stream'}));});document.querySelectorAll('[data-asset-delete]').forEach(b=>b.onclick=()=>{mutate(()=>state.assets.splice(+b.dataset.assetDelete,1));list();});};list();
  $('#pr-export').onclick=()=>{const payload={planId:PLAN.id,name:PLAN.name,current:clone(state),designs:clone(store.designs.filter(d=>d.planId===PLAN.id)),catalog:clone(store.custom||[])};try{const packed=P.pack(payload);P.previewPlan(P.unpack(packed),PLANS);const blob=new Blob([JSON.stringify(packed,null,2)],{type:'application/json'});if(blob.size>30e6)throw Error('项目文件超过 30 MB，请精简方案、模型或附件后导出');download(PLAN.id+'.furnish.json',blob);}catch(e){error(e);}};$('#pr-import').onclick=()=>$('#pr-file').click();$('#pr-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>30e6)throw Error('项目文件上限 30 MB');const payload=P.unpack(JSON.parse(await file.text()));content(`<h4>恢复预览</h4>${projectPreview(payload)}<p>当前工作方案将被替换；命名方案和家具库合并。原始基线不一致时创建新户型。</p><button class="btn primary" id="pr-restore-confirm">确认恢复此项目</button>`);$('#pr-restore-confirm').onclick=()=>{try{restore(payload);closeDialog();toast(t('完整项目已导入，当前方案可撤销。','Project imported; current work can be undone.'));}catch(err){error(err);}};}catch(err){error(err);}finally{e.target.value='';}};
  $('#pr-attach').onclick=()=>$('#pr-asset').click();$('#pr-asset').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2e6||(state.assets||[]).length>=5)throw Error('附件最多 5 个，每个上限 2 MB');const bytes=new Uint8Array(await file.arrayBuffer());let data='';for(let i=0;i<bytes.length;i+=0x8000)data+=String.fromCharCode(...bytes.subarray(i,i+0x8000));mutate(()=>{(state.assets||=[]).push({name:file.name.slice(0,150),data:btoa(data)});});list();}catch(err){error(err);}finally{e.target.value='';}};
 }
 function projectPreview(payload){
  const plan=P.previewPlan(payload,PLANS),work=payload.current,q=P.quantities(plan,work.architecture),outside=work.furniture.filter(f=>!P.fitsInRooms(plan.rooms,P.polygon(f))).length;
  const furniture=work.furniture.map(f=>`<polygon data-preview-furniture="${esc(f.id)}" points="${P.polygon(f).map(p=>p.join(',')).join(' ')}" fill="${/^#[0-9a-f]{3,8}$/i.test(f.color)?f.color:'#bd9d78'}" stroke="#685c4f" stroke-width="15" opacity=".75"/>`).join(''),windows=(plan.wins||[]).map(w=>`<rect x="${w.rect[0]}" y="${w.rect[1]}" width="${w.rect[2]-w.rect[0]}" height="${w.rect[3]-w.rect[1]}" fill="#dcecf8" stroke="#4f7394" stroke-width="15"/>`).join('');
  return `<div id="project-import-preview" data-preview-plan="${esc(plan.id)}"><p>${esc(payload.name||plan.name)} · ${q.rooms} 个房间 · 净面积 <b id="import-preview-area">${q.net.toFixed(2)}</b> m²</p>${planThumb(plan).replace('<svg ','<svg class="project-thumb" ').replace('</svg>',furniture+windows+'</svg>')}<p>${work.furniture.length} 件家具 · ${payload.designs.length} 份命名方案 · ${(work.assets||[]).length} 个附件 · ${(work.measures||[]).length} 条测量 · ${(work.notes||[]).length} 条标注</p><p>${work.architecture?(work.architecture.phase==='design'?'原始结构已锁定':'原始结构未锁定'):'内置户型方案'}；按文件中的布置、门窗和拆改生成预览。</p>${outside?`<p class="project-note" id="import-position-note">${outside} 件家具占地未完全位于房间范围内，载入后保留原位置。缩略图以墙体范围为主；载入后可定位检查，或主动点击“移回”。</p>`:''}<details><summary>查看门窗尺寸</summary><table class="project-table"><thead><tr><th>名称</th><th>宽 mm</th><th>高 mm</th><th>窗台高 mm</th></tr></thead><tbody>${P.openingSchedule(plan,work).map(o=>`<tr><td>${esc(o.name)}</td><td>${esc(o.width)}</td><td>${o.height}</td><td>${o.sill}</td></tr>`).join('')}</tbody></table></details></div>`;
 }
 function restore(input){input=P.unpack(P.pack(input));P.previewPlan(input,PLANS);const merged=P.mergeCatalog(store.custom||[],input,()=> 'c'+uid());let payload=merged.payload,id=payload.planId;
  if(payload.current.architecture){const existing=store.work[id]?.architecture;if(existing?.baseline&&JSON.stringify(existing.baseline)!==JSON.stringify(payload.current.architecture.baseline)){id='custom_'+uid();payload=P.copyProject(payload,id);}payload.current.plan=id;}
  const work=P.validateWork(payload.current),target=work.architecture?FurnishDraft.build(work.architecture.draft):PLANS.find(p=>p.id===id);if(!target)throw Error('旧方案引用了不存在的内置户型');const fixed=fixWork(work,target),incoming=payload.designs.map(d=>({id:'d'+uid(),name:d.name,planId:id,ts:d.ts||Date.now(),work:fixWork(P.validateWork(d.work),target)})),designs=P.mergeDesigns(store.designs,incoming,id);
  snapshot(true,state,'加载项目前');if(PLAN.id!==id&&store.work[id])snapshot(true,store.work[id],'加载项目前',id);registerCustomWork(fixed);
  if(PLAN.id!==id)setPlan(id);const before=snap();state=fixed;store.designs=designs;store.custom=merged.catalog;ui.sel=null;commit(before);renderAll();buildCats();buildLib();renderDesigns();buildPlanList();
 }
 function highlightIssue(item){
  $('#gSpaceFocus')?.remove();const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.id='gSpaceFocus';g.setAttribute('pointer-events','none');
  const polygons=[],f=getF(item.id);if(f){polygons.push(P.polygon(f));if(item.kind==='front'){const c=f.frontClearance??600,a=f.rot*Math.PI/180;polygons.push(P.polygon({...f,cx:f.cx-Math.sin(a)*(f.d/2+c/2),cy:f.cy+Math.cos(a)*(f.d/2+c/2),d:c}));}}
  if(item.otherId){const other=getF(item.otherId);if(other)polygons.push(P.polygon(other));}
  const d=DOORS[item.doorIndex];if(d){const points=[d.h];for(let i=0;i<=20;i++){const t=i/20*Math.PI/2;points.push([d.h[0]+d.len*(d.c[0]*Math.cos(t)+d.o[0]*Math.sin(t)),d.h[1]+d.len*(d.c[1]*Math.cos(t)+d.o[1]*Math.sin(t))]);}polygons.push(points);}
  g.innerHTML=polygons.map(p=>`<polygon points="${p.map(v=>v.join(',')).join(' ')}" fill="rgba(228,94,43,.15)" stroke="#e45e2b" stroke-width="3" vector-effect="non-scaling-stroke"/>`).join('')+(item.at?`<circle cx="${item.at[0]}" cy="${item.at[1]}" r="100" fill="none" stroke="#e45e2b" stroke-width="3" vector-effect="non-scaling-stroke"/>`:'')+`<title>${esc(item.message)}</title>`;svg.append(g);setTimeout(()=>g.remove(),8000);
 }
 function space(){content(`<p>${t('检查家具重叠／边缘越界、开门范围、墙体占用、柜门／抽屉正面空间，并扫描候选狭窄间隙。阈值是你的设计偏好；间隙扫描不等于完整通行路径判断；检查不是建筑合规或安全认证。定位会选中相关对象；相关家具、开启范围／正面空间或间隙点高亮 8 秒。忽略记录在几何变化后失效。','Check furniture overlaps and edges outside rooms, door swing, wall collisions, cabinet/drawer front space and candidate narrow gaps. Thresholds are design preferences; gap scanning is not route validation.')}</p><div class="project-grid">${field('space-passage',t('通道／间隙提醒阈值 mm','Gap warning threshold mm'),state.spaceThreshold||800,'number','min="300" max="2000"')}<button class="btn primary" id="space-run">${t('检查当前方案','Check current design')}</button></div><div id="space-results"></div>`);$('#space-run').onclick=()=>{try{const threshold=Number($('#space-passage').value),plan=planFor(state),issues=P.spaceCheck(plan,state.furniture,{passage:threshold});mutate(()=>state.spaceThreshold=threshold);const fingerprint=v=>P.checkFingerprint(v,plan,state.furniture,threshold);const ignored=state.spaceIgnored||[];$('#space-results').innerHTML=issues.length?`<table class="project-table">${issues.map((v,i)=>`<tr><td>${esc(v.name)}</td><td>${esc(v.message)}</td><td>${ignored.includes(fingerprint(v))?'已确认忽略 · ':''}<button class="btn" data-space-ignore="${i}">${ignored.includes(fingerprint(v))?'恢复提示':'确认后忽略'}</button><button class="btn" data-space-focus="${i}">${t('定位','Locate')}</button></td></tr>`).join('')}</table>`:`<p>${t('当前检查未发现问题。仍请核对家具实际开启方式。','No issues detected. Verify actual opening mechanisms.')}</p>`;document.querySelectorAll('[data-space-ignore]').forEach(b=>b.onclick=()=>{const key=fingerprint(issues[+b.dataset.spaceIgnore]);mutate(()=>state.spaceIgnored=ignored.includes(key)?ignored.filter(v=>v!==key):[...ignored.slice(-99),key]);$('#space-run').click();});document.querySelectorAll('[data-space-focus]').forEach(b=>b.onclick=()=>{const item=issues[+b.dataset.spaceFocus];closeDialog();if(item.doorIndex!==undefined){select({kind:'door',id:item.doorIndex});zoomToBox(DOORS[item.doorIndex].rect,500);}else if(item.kind==='passage'){select({kind:'room',id:item.id});zoomToBox(bbox(ROOMS.find(r=>r.id===item.id).poly),300);}else focusItem(item.id);highlightIssue(item);toast(item.message);});}catch(err){error(err);}};}
 function costs(){const q=P.quantities(planFor(state),state.architecture),rows=P.extraCosts(state.renovation||[],q);content(`<p>${t('家具、地面和乳胶漆由原报价计算。这里补充人工、拆改、水电、吊顶、防水、定制柜等费用，避免重复计价；单价由你输入。','Add labor, demolition, utilities, ceilings, waterproofing and cabinetry. Furniture/floors/paint are already included; enter your own rates and avoid double counting.')}</p><table class="project-table"><thead><tr><th>项目</th><th>工程量</th><th>单价</th><th>金额</th><th></th></tr></thead><tbody>${rows.items.map((r,i)=>`<tr><td>${esc(r.name)}<small> ${r.source==='manual'?'手填':'自动更新'}</small></td><td>${r.quantity.toFixed(2)} ${esc(r.unit)}</td><td>${yen(r.price)}</td><td>${yen(r.total)}</td><td><button class="btn" data-cost-edit="${i}">编辑</button><button class="btn" data-cost-delete="${i}">删除</button></td></tr>`).join('')}</tbody></table><p>${t('工程费用','Renovation costs')} ${yen(rows.total)} · ${t('全部预算','Total budget')} ${yen(budget().total)}</p><div class="project-grid">${field('cost-name',t('项目名称','Item name'),'人工')}${field('cost-unit',t('单位','Unit'),'项')}<label>${t('工程量来源','Quantity source')}<select id="cost-source"><option value="manual">手填工程量</option><option value="net">当前净面积 m²</option><option value="paint">墙面涂刷面积 m²</option><option value="removed">拆墙长度 m</option><option value="added">新建墙长度 m</option></select></label>${field('cost-quantity',t('手填工程量','Manual quantity'),1,'number','min="0" step="0.01"')}${field('cost-price',t('单价 ¥','Unit price ¥'),0,'number','min="0" step="0.01"')}<button class="btn primary" id="cost-add">${t('添加工程费用','Add cost')}</button></div><button class="btn" id="cost-export">${t('导出完整报价 CSV','Export full quote CSV')}</button>`);
  const rates=P.pricing(state.pricing);$('#project-content').insertAdjacentHTML('afterbegin',`<h4>材料单价与损耗</h4><p class="project-note">按当前方案保存，方案比较与报价导出同步使用；金额显示到元。留空材料单价使用默认参考价。</p><div class="project-grid">${field('rate-floor-waste','地面损耗 %',rates.floorWaste,'number','min="0" max="100"')}${field('rate-paint-waste','乳胶漆损耗 %',rates.paintWaste,'number','min="0" max="100"')}${field('rate-paint','乳胶漆单价 ¥/m²',rates.paintPrice,'number','min="0"')}${Object.entries(MATS).map(([id,m])=>field('rate-mat-'+id,nm(m.name)+' ¥/m²',rates.materials[id]??'','number','min="0" placeholder="'+Math.round(m.price)+'"')).join('')}</div><p><button class="btn primary" id="rate-save">应用预算参数</button><button class="btn" id="rate-reset">恢复默认预算参数</button></p>`);
  $('#rate-save').onclick=()=>{try{const number=id=>{if(!$('#'+id).value.trim())throw Error('损耗率和乳胶漆单价不可留空');return Number($('#'+id).value);},next=P.pricing({floorWaste:number('rate-floor-waste'),paintWaste:number('rate-paint-waste'),paintPrice:number('rate-paint'),materials:Object.fromEntries(Object.keys(MATS).filter(id=>$('#rate-mat-'+id).value.trim()).map(id=>[id,Number($('#rate-mat-'+id).value)]))});mutate(()=>state.pricing=next);open('budget');}catch(e){error(e);}};$('#rate-reset').onclick=()=>{mutate(()=>delete state.pricing);open('budget');};
  let editing=-1;$('#cost-source').onchange=()=>{const s=$('#cost-source').value;$('#cost-quantity').disabled=s!=='manual';if(s!=='manual')$('#cost-unit').value=['net','paint'].includes(s)?'m²':'m';};$('#cost-add').onclick=()=>{try{const row={name:$('#cost-name').value.trim(),unit:$('#cost-unit').value.trim(),source:$('#cost-source').value,quantity:Number($('#cost-quantity').value),price:Number($('#cost-price').value)},next=clone(state.renovation||[]);if(editing<0)next.push(row);else next[editing]=row;P.extraCosts(next,q);mutate(()=>state.renovation=next);open('budget');}catch(e){error(e);}};document.querySelectorAll('[data-cost-delete]').forEach(b=>b.onclick=()=>{mutate(()=>state.renovation.splice(+b.dataset.costDelete,1));open('budget');});document.querySelectorAll('[data-cost-edit]').forEach(b=>b.onclick=()=>{editing=+b.dataset.costEdit;const r=state.renovation[editing];for(const key of ['name','unit','source','quantity','price'])$('#cost-'+key).value=r[key];$('#cost-source').onchange();$('#cost-add').textContent=t('保存工程费用','Save cost');});$('#cost-export').onclick=exportCSV;
 }
 function products(){const selected=selItems()[0],list=state.furniture;content(`<p>${t('为实际家具记录品牌、型号、尺寸、单价、价格日期和购买链接。正面使用空间沿家具本地“下方”展开，可旋转家具以对准柜门方向。OBJ 模型按录入宽／高／深缩放，暂不导入贴图材质。','Record brand, model, dimensions, price/date and purchase URL. Front clearance follows local +Y; rotate to match opening direction. OBJ meshes scale to your dimensions; textures/material files are not imported.')}</p><label>${t('编辑已摆放家具','Edit placed item')} <select id="prod-select"><option value="">${t('新建品牌家具','New product')}</option>${list.map(f=>`<option value="${esc(f.id)}" ${f.id===selected?.id?'selected':''}>${esc(f.name)}</option>`).join('')}</select></label><div id="prod-form"></div>`);
  let obj=null;
  const form=()=>{const f=list.find(f=>f.id===$('#prod-select').value)||{name:'品牌家具',w:1000,d:600,h:800,price:0,frontClearance:600};let priceEdited=false;obj=f.obj||null;$('#prod-form').innerHTML=`<div class="project-grid" style="margin-top:15px">${[['name','名称',f.name],['brand','品牌',f.brand],['model','型号',f.model],['sourceUrl','购买／价格来源链接',f.sourceUrl],['priceDate','价格日期',f.priceDate]].map(([id,n,v])=>field('prod-'+id,n,v,id==='priceDate'?'date':'text')).join('')}${[['w','宽 mm',f.w],['d','深 mm',f.d],['h','高 mm',f.h??(f.id?'':800)],['price','单价 ¥',Math.round(priceOf(f))],['frontClearance','正面使用空间 mm',f.frontClearance??600]].map(([id,n,v])=>field('prod-'+id,n,v,'number','min="0"')).join('')}</div><p id="prod-mesh-status">${obj?t('已附带本地 OBJ 网格','Local OBJ mesh attached'):t('使用默认几何模型','Default geometry model')}</p><input id="prod-obj-file" type="file" accept=".obj" hidden><button class="btn" id="prod-obj">${t('导入 OBJ 模型','Import OBJ mesh')}</button><button class="btn" id="prod-clear-obj">${t('移除外部模型','Remove external mesh')}</button><button class="btn primary" id="prod-save">${t('保存家具资料','Save product')}</button><p class="project-note">${t('新家具也会加入“我的家具”库。来源链接仅记录，不自动抓取价格。','New products are added to My Items. URLs are references; prices are not fetched.')}</p>${/^https?:\/\//i.test(f.sourceUrl||'')?`<a href="${esc(f.sourceUrl)}" target="_blank" rel="noopener noreferrer">${t('打开购买／价格来源','Open product source')}</a>`:''}`;
   $('#prod-form').insertAdjacentHTML('afterbegin',`<div class="project-grid"><label>采购状态<select id="prod-purchaseStatus">${Object.entries(P.purchaseStates).map(([id,name])=>`<option value="${id}" ${id===(f.purchaseStatus||'planned')?'selected':''}>${esc(name)}</option>`).join('')}</select></label><label>采购备注<textarea id="prod-purchaseNote" maxlength="500" rows="3">${esc(f.purchaseNote||'')}</textarea></label></div>`);
   $('#prod-price').oninput=()=>priceEdited=true;for(const key of ['w','d','h'])$('#prod-'+key).disabled=!!f.locked;
   if(f.id){const checks=P.spaceCheck(planFor(state),state.furniture,{focusId:f.id,scanPassages:false});$('#prod-form').insertAdjacentHTML('beforeend',`<p class="project-note">${f.locked?t('家具已锁定，解锁后可改尺寸。','Unlock the item to resize it.'):t('改尺寸沿用家具属性中的尺寸调整基准。','Resizing uses the anchor chosen in item properties.')}</p><div role="status">${checks.map(v=>`<p class="project-error">${esc(v.message)}</p>`).join('')}</div>`);}
   $('#prod-obj').onclick=()=>$('#prod-obj-file').click();$('#prod-clear-obj').onclick=()=>{obj=null;$('#prod-mesh-status').textContent=t('已移除外部模型','External mesh removed');};$('#prod-obj-file').onchange=async e=>{try{const file=e.target.files[0];if(file.size>2e6)throw Error('OBJ 上限 2 MB');obj=P.parseOBJ(await file.text());$('#prod-mesh-status').textContent=file.name+' · '+obj.positions.length/9+' 三角面';}catch(err){error(err);}};
   $('#prod-save').onclick=()=>{try{const values=Object.fromEntries(['name','brand','model','sourceUrl','priceDate'].map(k=>[k,$('#prod-'+k).value.trim()]));values.purchaseStatus=$('#prod-purchaseStatus').value;values.purchaseNote=$('#prod-purchaseNote').value.trim();for(const k of ['w','d','h','price','frontClearance']){if(k==='h'&&f.id&&!$('#prod-'+k).value.trim())continue;if(!$('#prod-'+k).value.trim())throw Error('请填写尺寸、价格和使用空间');values[k]=Number($('#prod-'+k).value);}if(!values.name||values.name.length>80||['brand','model','sourceUrl'].some(k=>values[k].length>500)||values.sourceUrl&&!/^https?:\/\//i.test(values.sourceUrl)||![values.w,values.d,values.price,values.frontClearance,...(values.h===undefined?[]:[values.h])].every(Number.isFinite)||values.w<50||values.d<50||values.w>20000||values.d>20000||values.h<=0||values.h>20000||values.price<0||values.price>1e7||values.frontClearance<0||values.frontClearance>3000)throw Error('请检查名称、尺寸、价格、使用空间和 http(s) 链接');
    if(f.id){if(!priceEdited){delete values.price;if(values.name!==f.name&&f.price===undefined&&!['custom','customround'].includes(f.type))values.referencePrice=priceOf(f);}P.validateWork({furniture:[{...f,...values}]});mutate(()=>{const target=getF(f.id);if(target.locked){for(const k of ['w','d','h']){if(target[k]===undefined)delete values[k];else values[k]=target[k];}}const changed=['w','d','h'].some(k=>values[k]!==undefined&&target[k]!==values[k]),resized=changed?FurnishDesign.resizeFurniture(target,values):target;Object.assign(target,resized,values);if(obj)target.obj=clone(obj);else delete target.obj;});}else{if((store.custom||[]).length>=500||state.furniture.length>=2000)throw Error('家具库最多 500 条，每个方案最多 2000 件家具');const c={...values,id:'c'+uid(),shape:'rect',color:'#bd9d78',...(obj?{obj:clone(obj)}:{})};const center=ROOMS[0]?.at||[(PLAN.bounds.x+PLAN.bounds.w/2),(PLAN.bounds.y+PLAN.bounds.h/2)];const fresh=F('custom',c.name,center[0],center[1],c.w,c.d,0,c.color);Object.assign(fresh,values,{catalogId:c.id,catalogSnapshot:FurnishDesign.catalogSnapshot(c),...(obj?{obj:clone(obj)}:{})});mutate(()=>{(store.custom||=[]).push(c);state.furniture.push(fresh);});buildCats();buildLib();}toast(t('家具资料已保存','Product saved'));FurnishWorkspace.open('products');}catch(err){error(err);}};
  };$('#prod-select').onchange=form;form();
 }
 function wallPanel(id,panel){
  const a=currentArchitecture(),index=Number(id.slice(1)),rect=PLAN.walls[index];if(!rect){ui.sel=null;renderPanel();return;}
  const w=a?.draft.walls.find(w=>w.id===PLAN.wallRefs?.[index]),readonly=!w||a.phase==='design'&&w.kind!=='n',kind=w?.kind||rect[4];
  panel.innerHTML=`<section><h3>${kind==='b'?'承重墙':kind==='e'?'外墙':'非承重墙'}</h3><p>${readonly?(!w?'内置户型墙尺寸只读，请导入自定义户型。':'原始结构已确认：承重墙／外墙及其门窗锁定。'):'自定义墙属性修改可撤销，房间及面积自动重算。'}</p>${w?`<div class="project-grid">${field('wall-x','起点 X mm',w.a[0]*a.draft.scale,'number') }${field('wall-y','起点 Y mm',w.a[1]*a.draft.scale,'number')}${field('wall-length','中心线长度 mm',Math.hypot(w.b[0]-w.a[0],w.b[1]-w.a[1])*a.draft.scale,'number')}${field('wall-thickness','墙厚 mm',w.thickness,'number')}<label>墙类型<select id="wall-kind">${[['n','非承重'],['b','承重'],['e','外墙']].map(([k,n])=>`<option value="${k}" ${k===w.kind?'selected':''}>${n}</option>`).join('')}</select></label></div><button class="btn primary" id="wall-apply">应用墙属性</button>`:`<p>墙范围：${rect.slice(0,4).map(Math.round).join(' / ')} mm</p>`}<button class="btn" id="wall-editor">打开描图编辑器</button><p id="wall-error" class="project-error" role="alert"></p></section>`;
  panel.querySelectorAll('input,select,#wall-apply').forEach(el=>el.disabled=readonly);
  $('#wall-editor').onclick=()=>$('#tracePlan').click();
  if(w)$('#wall-apply').onclick=()=>{try{const next=clone(a.draft),wall=next.walls.find(v=>v.id===w.id),scale=next.scale,x=Number($('#wall-x').value)/scale,y=Number($('#wall-y').value)/scale,length=Number($('#wall-length').value)/scale,h=w.a[1]===w.b[1],sign=Math.sign(w.b[h?0:1]-w.a[h?0:1]),kind=$('#wall-kind').value;if(a.phase==='design'&&kind!=='n')throw Error('装修阶段只能调整非承重墙');Object.assign(wall,{a:[x,y],b:h?[x+length*sign,y]:[x,y+length*sign],thickness:Number($('#wall-thickness').value),kind});applyDraft(next);}catch(err){$('#wall-error').textContent='未应用：'+err.message;}};
  if(w){const ids=ui.sel.wallIds?.length?ui.sel.wallIds:[w.id],members=a.draft.walls.filter(v=>ids.includes(v.id)),locked=members.some(v=>a.phase==='design'&&v.kind!=='n');panel.insertAdjacentHTML('beforeend',`<section><b>已选 ${members.length} 段墙</b><p>Shift+点击追加墙段；连续多段线保留折墙编组。</p><button class="btn" id="wall-group-select" ${w.group?'':'disabled'}>选择整组折墙</button><button class="btn" id="wall-group-create">将所选墙段编组</button><button class="btn" id="wall-group-clear">取消所选编组</button>${field('wall-batch-thickness','批量墙厚 mm',w.thickness,'number','min="60" max="600"')}<button class="btn primary" id="wall-batch-apply" ${locked?'disabled':''}>应用到所选墙段</button><p>${locked?'所选包含锁定结构，不能批量改厚。':'墙厚以中心线向两侧展开，修改后净面积自动重算。'}</p></section>`);
    $('#wall-group-select').onclick=()=>select({...ui.sel,wallIds:a.draft.walls.filter(v=>v.group===w.group).map(v=>v.id)});
    const apply=values=>{try{applyDraft(FurnishDraft.batchWalls(a.draft,ids,values));}catch(e){$('#wall-error').textContent=e.message;}};$('#wall-group-create').onclick=()=>apply({group:'wall_group_'+uid()});$('#wall-group-clear').onclick=()=>apply({group:''});$('#wall-batch-apply').onclick=()=>apply({thickness:Number($('#wall-batch-thickness').value)});
  }
 }
 function bayPanel(index,panel){
  const a=currentArchitecture(),win=PLAN.wins[index],o=a?.draft.openings.find(v=>v.id===win?.bayId);if(!o?.bay)return false;
  const w=a.draft.walls.find(v=>v.id===o.wall),locked=a.phase==='design'&&w.kind!=='n';
  panel.innerHTML=`<section><h3>飘窗台与三面窗</h3><p>独立窗台不计入使用面积。位置沿基墙中心线，外凸方向自动朝向室外。</p><div class="project-grid">${field('bay-position','位置：距墙起点 mm',o.t*Math.hypot(w.b[0]-w.a[0],w.b[1]-w.a[1])*a.draft.scale,'number')}${field('bay-width','洞口宽 mm',o.length,'number','min="300" max="6000"')}${field('bay-depth','外凸进深 mm',o.bay.depth,'number','min="200" max="2000"')}${field('bay-height','窗台高 mm',o.bay.height,'number','min="100" max="1800"')}${field('bay-head','窗顶高 mm',o.bay.head,'number','max="2800"')}</div><button class="btn primary" id="bay-apply">应用飘窗属性</button><button class="btn" id="bay-remove">删除飘窗</button><button class="btn" id="bay-back">返回总览</button><p id="bay-error" class="project-error"></p><p>${locked?'已确认的原始外围墙及飘窗锁定，请复制原始户型重新核对。':'可撤销／重做；保存与备份保留全部尺寸。'}</p></section>`;
  panel.querySelectorAll('input,#bay-apply,#bay-remove').forEach(v=>v.disabled=locked);
  const apply=remove=>{try{const next=clone(a.draft),target=next.openings.find(v=>v.id===o.id);if(remove)next.openings=next.openings.filter(v=>v.id!==o.id);else{target.t=Number($('#bay-position').value)/(Math.hypot(w.b[0]-w.a[0],w.b[1]-w.a[1])*a.draft.scale);target.length=Number($('#bay-width').value);target.bay={depth:Number($('#bay-depth').value),height:Number($('#bay-height').value),head:Number($('#bay-head').value)};}applyDraft(next);select(null);}catch(e){$('#bay-error').textContent=e.message;}};
  $('#bay-apply').onclick=()=>apply(false);$('#bay-remove').onclick=()=>apply(true);$('#bay-back').onclick=()=>select(null);return true;
 }
 function windowPanel(index,panel){
  const a=currentArchitecture(),o=a?.draft.openings.find(v=>v.id===PLAN.winRefs?.[index]);if(!o||o.bay)return false;
  const win=PLAN.wins[index],wall=a.draft.walls.find(v=>v.id===o.wall),locked=a.phase==='design'&&wall.kind!=='n';
  panel.innerHTML=`<section><h3>窗尺寸</h3><p>窗高为实际洞口高度；窗顶高＝窗台高＋窗高。墙厚不作为窗高。</p><div class="project-grid">${field('window-width','窗宽 mm',Number(o.length.toFixed(2)),'number','min="300" max="6000" step="1"')}${field('window-height','窗高 mm',Math.round((win.head-win.sill)*1000),'number','min="100" max="2800" step="1"')}${field('window-sill','窗台高 mm',Math.round(win.sill*1000),'number','min="0" max="2400" step="1"')}</div><p>窗顶高：${Math.round(win.head*1000)} mm</p><button class="btn primary" id="window-apply">应用尺寸</button><button class="btn" id="window-edit">打开结构编辑器</button><button class="btn" id="window-back">返回总览</button><p id="window-error" class="project-error"></p><p>${locked?'原始结构已锁定：在结构编辑器中点击“解锁并重新核对原始结构”，修改后重新确认。':'修改同步三维与墙面工程量，支持撤销／重做。'}</p></section>`;
  panel.querySelectorAll('input,#window-apply').forEach(el=>el.disabled=locked);
  $('#window-apply').onclick=()=>{try{const next=clone(a.draft),target=next.openings.find(v=>v.id===o.id),sill=Number($('#window-sill').value),height=Number($('#window-height').value);if(!Number.isFinite(height)||height<100)throw Error('窗高至少100 mm');Object.assign(target,{length:Number($('#window-width').value),sill,head:sill+height});applyDraft(next,o.id);}catch(e){$('#window-error').textContent=e.message;}};
  $('#window-edit').onclick=()=>$('#tracePlan').click();$('#window-back').onclick=()=>select(null);return true;
 }
 function exportPlan(id){try{const plan=PLANS.find(p=>p.id===id);if(!plan)throw Error('户型不存在');const work=id===PLAN.id?state:store.work[id]||freshWork(plan),packed=P.pack({planId:id,name:plan.name,current:clone(work),designs:clone(store.designs.filter(d=>d.planId===id)),catalog:clone(store.custom||[])});P.previewPlan(P.unpack(packed),PLANS);const blob=new Blob([JSON.stringify(packed,null,2)],{type:'application/json'});if(blob.size>30e6)throw Error('项目文件超过30 MB');download(id+'.furnish.json',blob);}catch(e){toast(e.message);}}
 function importProject(){
  const input=document.createElement('input');input.type='file';input.accept='.json,.furnish';input.hidden=true;input.id='gallery-project-file';document.body.append(input);
  input.oncancel=()=>input.remove();input.onchange=async()=>{try{const file=input.files[0];if(!file)return;if(file.size>30e6)throw Error('文件上限30 MB');let payload=P.unpack(JSON.parse(await file.text()));if(payload.current.architecture&&PLANS.some(p=>p.id===payload.planId))payload=P.copyProject(payload,'custom_'+uid());const preview=projectPreview(payload);openDialog({title:'加载户型／项目文件',wide:true,body:`${preview}<p>${payload.current.architecture?'将作为独立自定义户型加入户型库，已有同名户型保留。':'这是内置户型方案，将恢复该户型的布置与门窗设置。'}</p><p id="gallery-import-error" class="project-error"></p>`,actions:[{label:'取消'},{label:'加载并编辑',cls:'primary',fn:()=>{try{restore(payload);return true;}catch(e){$('#gallery-import-error').textContent=e.message;return false;}}}]});}catch(e){toast('无法加载：'+e.message);}finally{input.remove();}};input.click();
 }
 function locateIssue(item){closeDialog();if(item.doorIndex!==undefined){select({kind:'door',id:item.doorIndex});zoomToBox(DOORS[item.doorIndex].rect,500);}else if(item.kind==='passage'){select({kind:'room',id:item.id});zoomToBox(bbox(ROOMS.find(r=>r.id===item.id).poly),300);}else focusItem(item.id);highlightIssue(item);toast(item.message);}
 window.FurnishWorkspace={locateIssue,open,demolish,afterRender,summary,restore,wallPanel,bayPanel,windowPanel,exportPlan,importProject};afterRender();
 const loading=document.createElement('div');loading.style.cssText='position:fixed;inset:0;z-index:110;display:grid;place-items:center;background:rgba(250,248,242,.85);color:#343029';loading.textContent=t('正在读取本地项目…','Loading local projects…');document.body.append(loading);
 let timeout=setTimeout(()=>loading.remove(),4000);
 window.FurnishStorage?.ready.then(saved=>{
   if(storageWiping)return;
   if(!saved||saved.v!==2||!(saved.updatedAt>(store.updatedAt||0)))return;
   const drafts=(saved.customPlans||[]).map(d=>FurnishDraft.build(saved.work[d.id]?.architecture?.draft||d));
   const validated=Object.fromEntries(Object.entries(saved.work||{}).map(([id,w])=>[id,P.validateWork(w)]));
   for(const plan of drafts){const existing=PLANS.find(p=>p.id===plan.id);if(existing)Object.assign(existing,plan);else PLANS.push(plan);}
   const target=PLANS.find(p=>p.id===saved.planId);if(!target)throw Error('Saved project references an unknown plan');
   store=saved;store.work=validated;PLAN=target;state=fixWork(store.work[PLAN.id]||freshWork(PLAN),PLAN);customArchDraft=null;customArchPlanId='';ui.sel=null;undoStack.length=redoStack.length=0;applyPlanData();buildDefs();buildCats();buildLib();renderOpenings();renderDims();renderAll();fitView();renderDesigns();buildPlanList();window.View3D?.replan();savedAt=store.updatedAt;saveErr=false;syncSaved();
 }).catch(e=>{toast(t('较大项目本地备份未能恢复，请检查项目文件备份：','Could not recover the larger local save; check your project file backup: ')+e.message);}).finally(()=>{clearTimeout(timeout);loading.remove();});
})();
